#!/usr/bin/env php
<?php

echo "Updating db";

$handle = fopen("App/.env", "r");
if ($handle) {
    while (($line = fgets($handle)) !== false) {
        $var = explode("=", $line);
        $key = ltrim(rtrim($var[0]));
        $$key = ltrim(rtrim($var[1]));
    }

    fclose($handle);
} else {
}

$db = new mysqli($DB_HOST, $DB_USER, $DB_PASSWORD);

$database = $DB_NAME;
$db->query('use information_schema');

$query = "SELECT * from `SCHEMATA` WHERE `SCHEMA_NAME`='$database';";
echo "\nDB name : $database";
$res = $db->query($query);
if (mysqli_num_rows($res)) {
    print("\nDatabase already exists!");
    print("\nWould you like to reset db? (y/n) : ");
    $input = rtrim(fgets(STDIN));
    if ($input == "y") {
        $db->query("DROP DATABASE $database;");
    } else {
        exit("exited!");
    }
}
$db->query("Create DATABASE $database;");
$db->query("use $database;");
print("\nSetting up...");
$commands = file_get_contents("$database.sql");
$db->multi_query($commands);
print("\nCompleted!");
?>